# handler for adapter tykgrpcadapter
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
 name: h1
 namespace: istio-system
spec:
 adapter: tykgrpcadapter
 connection:
   address: "{ADDRESS}" #replaces at runtime by the test
 params:
   gateway_url: "localhost:8080"
